# Generated by Django 6.1.1 on 2026-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_listing_category_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pets',
            field=models.BooleanField(default=False),
        ),
    ]
