# Generated by Django 6.1.1 on 2026-09-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_booking_id_alter_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.JSONField(blank=True, default=list, max_length=10),
        ),
    ]
