# Generated by Django 6.1.1 on 2026-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_listing_host_alter_listing_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='host',
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.JSONField(blank=True, default=list, max_length=10),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
