# Generated by Django 5.1.5 on 2026-09-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_listing_owner_alter_booking_id_alter_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
